/*
 * JSP generated by Resin-4.0.23 (built Fri, 30 Sep 2011 09:31:50 PDT)
 */

package _jsp._web_22dinf._jsp._tuiguang;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _list__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_1 = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    pageContext.include("/inc/header.jsp", false);out.write(_jsp_string1, 0, _jsp_string1.length);
    _jsp_loop_1 = _jsp_state.get_jsp_loop_1(pageContext, _jsp_parent_tag);
    java.lang.Object _jsp_items_2 = _caucho_expr_0.evalObject(_jsp_env);
    java.util.Iterator _jsp_iter_2 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_2);
    _jsp_loop_1.init(0, Integer.MAX_VALUE, 1, false, false, false);
    while (_jsp_iter_2.hasNext()) {
      Object _jsp_i_2 = _jsp_iter_2.next();
      _jsp_loop_1.setCurrent(_jsp_i_2, _jsp_iter_2.hasNext());
      pageContext.setAttribute("citys", _jsp_i_2);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _caucho_expr_1.print(out, _jsp_env, false);
      out.write(_jsp_string3, 0, _jsp_string3.length);
      _caucho_expr_2.print(out, _jsp_env, false);
      out.write('>');
      _caucho_expr_3.print(out, _jsp_env, false);
      out.write(_jsp_string4, 0, _jsp_string4.length);
    }
    pageContext.pageSetOrRemove("citys", null);
    out.write(_jsp_string5, 0, _jsp_string5.length);
    _caucho_expr_4.print(out, _jsp_env, false);
    out.write(_jsp_string6, 0, _jsp_string6.length);
    _caucho_expr_5.print(out, _jsp_env, false);
    out.write(_jsp_string7, 0, _jsp_string7.length);
    _jsp_loop_1 = _jsp_state.get_jsp_loop_1(pageContext, _jsp_parent_tag);
    java.lang.Object _jsp_items_3 = _caucho_expr_6.evalObject(_jsp_env);
    java.util.Iterator _jsp_iter_3 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_3);
    _jsp_loop_1.init(0, Integer.MAX_VALUE, 1, false, false, false);
    while (_jsp_iter_3.hasNext()) {
      Object _jsp_i_3 = _jsp_iter_3.next();
      _jsp_loop_1.setCurrent(_jsp_i_3, _jsp_iter_3.hasNext());
      pageContext.setAttribute("brands", _jsp_i_3);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _caucho_expr_7.print(out, _jsp_env, false);
      out.write(_jsp_string3, 0, _jsp_string3.length);
      _caucho_expr_8.print(out, _jsp_env, false);
      out.write('>');
      _caucho_expr_9.print(out, _jsp_env, false);
      out.write(' ');
      _caucho_expr_10.print(out, _jsp_env, false);
      out.write(_jsp_string4, 0, _jsp_string4.length);
    }
    pageContext.pageSetOrRemove("brands", null);
    out.write(_jsp_string8, 0, _jsp_string8.length);
    _caucho_expr_11.print(out, _jsp_env, false);
    out.write(_jsp_string9, 0, _jsp_string9.length);
    _caucho_expr_12.print(out, _jsp_env, false);
    out.write(_jsp_string10, 0, _jsp_string10.length);
    if (_caucho_expr_13.evalBoolean(_jsp_env)) {
      out.write(_jsp_string11, 0, _jsp_string11.length);
      _jsp_loop_1 = _jsp_state.get_jsp_loop_1(pageContext, _jsp_parent_tag);
      java.lang.Object _jsp_items_4 = _caucho_expr_14.evalObject(_jsp_env);
      java.util.Iterator _jsp_iter_4 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_4);
      _jsp_loop_1.init(0, Integer.MAX_VALUE, 1, false, false, false);
      while (_jsp_iter_4.hasNext()) {
        Object _jsp_i_4 = _jsp_iter_4.next();
        _jsp_loop_1.setCurrent(_jsp_i_4, _jsp_iter_4.hasNext());
        pageContext.setAttribute("promoList", _jsp_i_4);
        out.write(_jsp_string12, 0, _jsp_string12.length);
        _caucho_expr_15.print(out, _jsp_env, false);
        out.write(_jsp_string13, 0, _jsp_string13.length);
        _caucho_expr_16.print(out, _jsp_env, false);
        out.write(_jsp_string13, 0, _jsp_string13.length);
        _caucho_expr_17.print(out, _jsp_env, false);
        out.write(_jsp_string14, 0, _jsp_string14.length);
        if (_caucho_expr_18.evalBoolean(_jsp_env)) {
          out.write(_jsp_string15, 0, _jsp_string15.length);
        }
        out.write(_jsp_string16, 0, _jsp_string16.length);
        if (_caucho_expr_19.evalBoolean(_jsp_env)) {
          out.write(_jsp_string17, 0, _jsp_string17.length);
        }
        out.write(_jsp_string16, 0, _jsp_string16.length);
        if (_caucho_expr_20.evalBoolean(_jsp_env)) {
          _caucho_expr_21.print(out, _jsp_env, false);
        }
        out.write(_jsp_string18, 0, _jsp_string18.length);
        _caucho_expr_22.print(out, _jsp_env, false);
        out.write(_jsp_string19, 0, _jsp_string19.length);
        _caucho_expr_23.print(out, _jsp_env, false);
        out.write(_jsp_string19, 0, _jsp_string19.length);
        _caucho_expr_24.print(out, _jsp_env, false);
        out.write(_jsp_string20, 0, _jsp_string20.length);
        _caucho_expr_25.print(out, _jsp_env, false);
        out.write(_jsp_string21, 0, _jsp_string21.length);
        _caucho_expr_15.print(out, _jsp_env, false);
        out.write(_jsp_string22, 0, _jsp_string22.length);
        _caucho_expr_15.print(out, _jsp_env, false);
        out.write(_jsp_string23, 0, _jsp_string23.length);
      }
      pageContext.pageSetOrRemove("promoList", null);
      out.write(_jsp_string24, 0, _jsp_string24.length);
    }
    out.write(_jsp_string24, 0, _jsp_string24.length);
    if (_caucho_expr_26.evalBoolean(_jsp_env)) {
      out.write(_jsp_string25, 0, _jsp_string25.length);
    }
    out.write(_jsp_string26, 0, _jsp_string26.length);
    pageContext.include("/WEB-INF/snippets/page.jsp", false);out.write(_jsp_string27, 0, _jsp_string27.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -1793038186146849453L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/jsp/tuiguang/list.jsp"), 8774515524745751927L, false);
    _caucho_depends.add(depend);
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_1;

    final com.caucho.jsp.IteratorLoopSupportTag get_jsp_loop_1(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_loop_1 == null) {
        _jsp_loop_1 = new com.caucho.jsp.IteratorLoopSupportTag();
        _jsp_loop_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      return _jsp_loop_1;
    }

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
      manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jsp/jstl/fmt");
      manager.addTaglibFunctions(_jsp_functionMap, "func", "/WEB-INF/func.tld");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${citys }");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${citys.value.id }");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${citys.value.id==promotion.cityId?'selected':'' }");
      _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${citys.value.orderName}");
      _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promotion.brandId==-1?'selected':'' }");
      _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promotion.brandId==0?'selected':'' }");
      _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${brands }");
      _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${brands.id }");
      _caucho_expr_8 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${brands.id==promotion.brandId?'selected':'' }");
      _caucho_expr_9 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${brands.orderName}");
      _caucho_expr_10 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${brands.name }");
      _caucho_expr_11 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promotion.startTime }");
      _caucho_expr_12 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promotion.endTime }");
      _caucho_expr_13 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promoList!=null&&promoList.size()>0 }");
      _caucho_expr_14 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promoList }");
      _caucho_expr_15 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promoList.id }");
      _caucho_expr_16 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${func:getallCity(promoList.cityId)}");
      _caucho_expr_17 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promoList.cityCode }");
      _caucho_expr_18 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promoList.brandId==-1 }");
      _caucho_expr_19 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promoList.brandId==0 }");
      _caucho_expr_20 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promoList.brandId>0 }");
      _caucho_expr_21 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${func:getBrandName(promoList.brandId) }");
      _caucho_expr_22 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promoList.money }");
      _caucho_expr_23 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promoList.spendTime }");
      _caucho_expr_24 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promoList.addTime }");
      _caucho_expr_25 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${func:getEditName(promoList.adminId)}");
      _caucho_expr_26 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${promoList==null||promoList.size()<=0 }");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;
  private static com.caucho.el.Expr _caucho_expr_8;
  private static com.caucho.el.Expr _caucho_expr_9;
  private static com.caucho.el.Expr _caucho_expr_10;
  private static com.caucho.el.Expr _caucho_expr_11;
  private static com.caucho.el.Expr _caucho_expr_12;
  private static com.caucho.el.Expr _caucho_expr_13;
  private static com.caucho.el.Expr _caucho_expr_14;
  private static com.caucho.el.Expr _caucho_expr_15;
  private static com.caucho.el.Expr _caucho_expr_16;
  private static com.caucho.el.Expr _caucho_expr_17;
  private static com.caucho.el.Expr _caucho_expr_18;
  private static com.caucho.el.Expr _caucho_expr_19;
  private static com.caucho.el.Expr _caucho_expr_20;
  private static com.caucho.el.Expr _caucho_expr_21;
  private static com.caucho.el.Expr _caucho_expr_22;
  private static com.caucho.el.Expr _caucho_expr_23;
  private static com.caucho.el.Expr _caucho_expr_24;
  private static com.caucho.el.Expr _caucho_expr_25;
  private static com.caucho.el.Expr _caucho_expr_26;

  private final static char []_jsp_string10;
  private final static char []_jsp_string15;
  private final static char []_jsp_string12;
  private final static char []_jsp_string3;
  private final static char []_jsp_string5;
  private final static char []_jsp_string24;
  private final static char []_jsp_string20;
  private final static char []_jsp_string2;
  private final static char []_jsp_string16;
  private final static char []_jsp_string14;
  private final static char []_jsp_string17;
  private final static char []_jsp_string22;
  private final static char []_jsp_string0;
  private final static char []_jsp_string7;
  private final static char []_jsp_string11;
  private final static char []_jsp_string1;
  private final static char []_jsp_string27;
  private final static char []_jsp_string21;
  private final static char []_jsp_string13;
  private final static char []_jsp_string25;
  private final static char []_jsp_string4;
  private final static char []_jsp_string19;
  private final static char []_jsp_string18;
  private final static char []_jsp_string9;
  private final static char []_jsp_string26;
  private final static char []_jsp_string6;
  private final static char []_jsp_string8;
  private final static char []_jsp_string23;
  static {
    _jsp_string10 = "\" readonly=\"readonly\" autocomplete=\"off\" />\r\n	                      	</div>\r\n	          		</label>\r\n	          		<div style=\"text-align: center\">\r\n		          		<input type=\"submit\" value=\"\u67e5\u8be2\" class=\"btn btn-info\"/>&nbsp;&nbsp;\r\n		          		<input type=\"button\" value=\"\u6e05\u7a7a\" class=\"btn btn-info\" onclick=\"javascript:clearSearch();\"/>&nbsp;&nbsp;\r\n	          		</div>\r\n	          	</div>\r\n	         </div>\r\n		</div>\r\n		<div class=\"rb-con\">\r\n			<div class=\"over-auto\">\r\n				<table class=\"table table-bordered chargeTable\">\r\n					\r\n				</table>\r\n			</div>\r\n		</div>\r\n		<div class=\"rb-con\">\r\n			<div class=\"over-auto\">\r\n				<table class=\"table table-bordered chargeTable\">\r\n					<tr>\r\n						<td style=\"text-align: center;\">ID</td>\r\n						<td style=\"text-align: center;\">\u57ce\u5e02</td>\r\n						<td style=\"text-align: center;\">\u57ce\u5e02\u7f16\u7801</td>\r\n						<td style=\"text-align: center;\">\u54c1\u724c</td>\r\n						<td style=\"text-align: center;\">\u63a8\u5e7f\u8d39\u7528</td>\r\n						<td style=\"text-align: center;\">\u63a8\u5e7f\u65f6\u95f4</td>\r\n						<td style=\"text-align: center;\">\u521b\u5efa\u65f6\u95f4</td>\r\n						<td style=\"text-align: center;\">\u64cd\u4f5c\u4eba</td>\r\n						<td style=\"text-align: center;\">\u64cd\u4f5c</td>\r\n					</tr>\r\n					".toCharArray();
    _jsp_string15 = "\u5176\u4ed6".toCharArray();
    _jsp_string12 = "\r\n							<tr>\r\n								<td style=\"text-align: center;\" width=\"50px\">".toCharArray();
    _jsp_string3 = "\" ".toCharArray();
    _jsp_string5 = "\r\n						</select>\r\n	          		</label>\r\n	          		<label class=\"pr15\">\u9009\u62e9\u54c1\u724c:\r\n	          			<select id=\"brandId\" name=\"brandId\">\r\n							<option value=\"\">\u8bf7\u9009\u62e9</option>\r\n							<option value=\"-1\" ".toCharArray();
    _jsp_string24 = "\r\n					".toCharArray();
    _jsp_string20 = "</td>\r\n								<td style=\"text-align: center;\" width=\"50px\">".toCharArray();
    _jsp_string2 = "\r\n								<option value=\"".toCharArray();
    _jsp_string16 = "\r\n									".toCharArray();
    _jsp_string14 = "</td>\r\n								<td style=\"text-align: center;\" width=\"200px\">\r\n									".toCharArray();
    _jsp_string17 = "\u6c7d\u8f66\u56e2\u8d2d".toCharArray();
    _jsp_string22 = "\">\u4fee\u6539</a>\r\n									<a href=\"javascript:deleteOne(".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string7 = ">\u6c7d\u8f66\u56e2\u8d2d</option>\r\n							".toCharArray();
    _jsp_string11 = "\r\n						".toCharArray();
    _jsp_string1 = "\r\n<title>\u63a8\u5e7f\u67e5\u8be2</title>\r\n</head>\r\n<body>\r\n<form id=\"listForm\" enctype=\"multipart/form-data\" action=\"/promo/tolist\" method=\"POST\">\r\n	<div id=\"man_zone\">\r\n		<div>\u6279\u91cf\u5bfc\u5165\r\n			<span class=\"add-on\"><i class=\"icon-calendar\"></i></span>\r\n			\u5bfc\u5165\u65e5\u671f\uff1a<input id=\"spendTime\" type='text' name='spendTime' class=\"querytime span2\" readonly=\"readonly\" autocomplete=\"off\" />\r\n			<input type=\"file\" name=\"file\" id=\"file\" />\r\n			<input id=\"import\" name=\"import\" type=\"button\" value=\"\u4e0a\u4f20\" class=\"btn\" onclick=\"importSubmit()\"/>\r\n		</div>\r\n		<div>\r\n			<div class=\"b-con a-form\">\r\n	          	<div class=\"pd5\">\r\n	          		<label class=\"pr15\">\u9009\u62e9\u57ce\u5e02:\r\n	          			<select id=\"cityId\" name=\"cityId\">\r\n							<option value=\"\">\u8bf7\u9009\u62e9</option>\r\n							".toCharArray();
    _jsp_string27 = "\r\n	</div>\r\n</form>\r\n<script type=\"text/javascript\">\r\n$('.querytime').live(\"click\",function() {\r\n	WdatePicker({\r\n	isShowClear:true,\r\n	qsEnabled:false,\r\n	dateFmt:'yyyy-MM-dd'\r\n	});\r\n	});\r\n	function clearSearch(){\r\n		$(\"#id\").val('');\r\n		$(\"#adminId\").val('');\r\n		$(\"#brandId\").val('');\r\n		$(\"#cityId\").val('');\r\n		$(\"#minMoney\").val('');\r\n		$(\"#maxMoney\").val('');\r\n		$(\"#starttime\").val('');\r\n		$(\"#endtime\").val('');\r\n		$(\"#listForm\").submit();\r\n	}\r\n	\r\n	function importSubmit(){\r\n		if($(\"#spendTime\").val()==''){\r\n			alert(\"\u8bf7\u9009\u62e9\u5bfc\u5165\u65f6\u95f4\uff01\");\r\n			return false;\r\n		}\r\n		if($(\"#file\").val()==''){\r\n			alert(\"\u8bf7\u9009\u62e9\u4e0a\u4f20\u7684\u6587\u4ef6\uff01\");\r\n			return false;\r\n		}\r\n		\r\n		var str=$(\"#file\").val();\r\n		var pos=str.lastIndexOf(\".\");\r\n		var lastname = str.substring(pos,str.length); \r\n		if(lastname!='.xlsx'&&lastname!='.xls'){\r\n			alert(\"\u6587\u4ef6\u683c\u5f0f\u4e0d\u652f\u6301\uff0c\u8bf7\u4e0a\u4f20 xlsx\u6216\u8005xls \u683c\u5f0f\u7684\u6587\u4ef6\");\r\n			return false;\r\n		}\r\n		$(\"#listForm\").attr(\"action\",\"/promo/excleImport\");\r\n		$(\"#listForm\").attr(\"method\",\"post\");\r\n		$(\"#listForm\").submit();\r\n	}\r\n	\r\n	function deleteOne(id){\r\n		if(!confirm(\"\u6b64\u9879\u4e3a\u771f\u5b9e\u5220\u9664,\u8bf7\u786e\u8ba4\")){\r\n			return;\r\n		}\r\n		$.ajax({\r\n			type:'post',\r\n			url:'/promo/delete',\r\n			dataType:'text',\r\n			data:{\r\n				id:id,\r\n			},\r\n			success:function(data){\r\n				if(data!=null){\r\n					alert(data);\r\n					$(\"#listForm\").submit();\r\n				}\r\n			}\r\n		})\r\n	}\r\n</script>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string21 = "</td>\r\n								<td style=\"text-align: center;\" width=\"50px\">\r\n									<a href=\"/promo/preUpdate?id=".toCharArray();
    _jsp_string13 = "</td>\r\n								<td style=\"text-align: center;\" width=\"150px\">".toCharArray();
    _jsp_string25 = "\r\n						<tr>\r\n							<td colspan=\"8\">\u6ca1\u6709\u6570\u636e</td>\r\n						</tr>\r\n					".toCharArray();
    _jsp_string4 = "</option>\r\n							".toCharArray();
    _jsp_string19 = "</td>\r\n								<td style=\"text-align: center;\" width=\"200px\">".toCharArray();
    _jsp_string18 = "\r\n								</td>\r\n								<td style=\"text-align: center;\" width=\"200px\">".toCharArray();
    _jsp_string9 = "\" readonly=\"readonly\" autocomplete=\"off\" />\r\n	                      	</div>-\r\n	                    	<div class=\"input-prepend\">\r\n	                      		<span class=\"add-on\"><i class=\"icon-calendar\"></i></span>\r\n	                      		<input type='text' id=\"endtime\" name='endTime' class=\"querytime span2\" value=\"".toCharArray();
    _jsp_string26 = "\r\n		          </table>\r\n		     </div>\r\n		</div>\r\n	</div>\r\n	<div class=\"page_and_btn\" style=\"text-align:center;\">\r\n   		".toCharArray();
    _jsp_string6 = ">\u5176\u4ed6</option>\r\n							<option value=\"0\" ".toCharArray();
    _jsp_string8 = "\r\n						</select>\r\n	          		</label>\r\n	          		<label class=\"pr15\">\r\n	          				\u63a8\u5e7f\u65e5\u671f:\r\n	          				<div class=\"input-prepend\">\r\n	                      		<span class=\"add-on\"><i class=\"icon-calendar\"></i></span>\r\n	                      		<input id=\"starttime\" type='text' name='startTime' class=\"querytime span2\" value=\"".toCharArray();
    _jsp_string23 = ");\" >\u5220\u9664</a>\r\n								</td>\r\n							</tr>\r\n						".toCharArray();
  }
}
