/*
 * JSP generated by Resin-4.0.23 (built Fri, 30 Sep 2011 09:31:50 PDT)
 */

package _jsp._inc;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _header__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html");

     String jsversion="201404141631";
    out.write(_jsp_string0, 0, _jsp_string0.length);
    out.print((jsversion));
    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((jsversion));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((jsversion));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((jsversion));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((jsversion));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((jsversion));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((jsversion));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((jsversion));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((jsversion));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((jsversion));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((jsversion));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.print((jsversion));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((jsversion));
    out.write(_jsp_string13, 0, _jsp_string13.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -1793038186146849453L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("inc/header.jsp"), -32468967561455081L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string11;
  private final static char []_jsp_string6;
  private final static char []_jsp_string2;
  private final static char []_jsp_string4;
  private final static char []_jsp_string8;
  private final static char []_jsp_string12;
  private final static char []_jsp_string3;
  private final static char []_jsp_string10;
  private final static char []_jsp_string1;
  private final static char []_jsp_string9;
  private final static char []_jsp_string7;
  private final static char []_jsp_string13;
  private final static char []_jsp_string0;
  private final static char []_jsp_string5;
  static {
    _jsp_string11 = "\" charset=\"UTF-8\"></script>\n<script type=\"text/javascript\" src=\"/js/base.js?v=".toCharArray();
    _jsp_string6 = "\"></script>\n<script type=\"text/javascript\" src=\"/js/jquery.js?v=".toCharArray();
    _jsp_string2 = "\" />\n<link type=\"text/css\" rel=\"stylesheet\" href=\"/css/common.css?v=".toCharArray();
    _jsp_string4 = "\"/>\n<![endif]-->\n<link type=\"text/css\" rel=\"stylesheet\" href=\"/css/zTreeStyle.css?v=".toCharArray();
    _jsp_string8 = "\" charset=\"UTF-8\"></script>\n<script type=\"text/javascript\" src=\"/js/jquery.form.js?v=".toCharArray();
    _jsp_string12 = "\" charset=\"UTF-8\"></script>\n<script type=\"text/javascript\" src=\"/js/ztree.js?v=".toCharArray();
    _jsp_string3 = "\" />\n<!--[if lt IE 9]>\n<link type=\"text/css\" rel=\"stylesheet\" href=\"/css/jquery.ui.ie.css?v=".toCharArray();
    _jsp_string10 = "\" charset=\"UTF-8\"></script>\n<script type=\"text/javascript\" src=\"/js/jquery.metadata.js?v=".toCharArray();
    _jsp_string1 = "\" />\n<link type=\"text/css\" rel=\"stylesheet\" href=\"/css/bootstrap.min.css?v=".toCharArray();
    _jsp_string9 = "\" charset=\"UTF-8\"></script>\n<script type=\"text/javascript\" src=\"/js/jquery.validate.js?v=".toCharArray();
    _jsp_string7 = "\" charset=\"UTF-8\"></script>\n<script type=\"text/javascript\" src=\"/js/bootstrap.js?v=".toCharArray();
    _jsp_string13 = "\" charset=\"UTF-8\"></script>".toCharArray();
    _jsp_string0 = "\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n<link type=\"text/css\" rel=\"stylesheet\" href=\"/css/base.css?v=".toCharArray();
    _jsp_string5 = "\" />\n<script type=\"text/javascript\" src=\"/js/WdatePicker/WdatePicker.js?v=".toCharArray();
  }
}
