
	<div class="seo_bottom_wrap" style="width:auto;">
    	<h3 class="seo_info_tit">一键报名，获取市场真实底价</h3>
        <div class="seo_info_wrap clearfix">
        	<div class="sbw_left fl">
            	 <div class="seo_info_tip">
                    <p class="seo_tip_con">报名询价，拿到最真实的市场成交价</p>
                </div>
                <form class="form_3 form_seo form_bottom" id="seo_form_bottom" action="http://tuanche.com/service/signup/formapply/" method="post">
                    <div class="form_control">
                    	<input type="hidden" name="bmtype" value="zt_detail" /> 
					    <input type="hidden" name="position" value="2" />
                        <label class="f_label">城市</label>
                        <div class="controls">
                             <div class="selects click_selects_seo" id="car_select_city_bottom">
                                <input type="text" name="city" class="inpt hide seo_city" autocomplete="off">
                                <span class="help-inline"></span>
                                <div class="select_selected">
                                    <span class="select_val">选择城市</span>
                                    <i class="down_arr"></i>
                                </div>
                                <div class="select_con select_city"></div>
                            </div>
                        </div>
                    </div>
                    <div class="form_control">
                        <label class="f_label">品牌</label>
                        <div class="controls">
                             <div class="selects click_selects_seo disabled_click" id="car_select_brand_bottom">
                                <input type="text" name="brand" class="inpt hide" autocomplete="off">
                                <span class="help-inline"></span>
                                <div class="select_selected">
                                    <span class="select_val">选择品牌</span>
                                    <i class="down_arr"></i>
                                </div>
                                <div class="select_con select_brand"></div>
                            </div>
                        </div>
                    </div>
                    <div class="form_control">
                        <label class="f_label">车型</label>
                        <div class="controls">
                             <div class="selects click_selects_seo disabled_click" id="car_select_style_bottom">
                                <input type="text" name="carStyle" class="inpt hide" autocomplete="off">
                                <span class="help-inline"></span>
                                <div class="select_selected">
                                    <span class="select_val">选择车型</span>
                                    <i class="down_arr"></i>
                                </div>
                                <div class="select_con select_style"></div>
                            </div>
                        </div>
                    </div>
                    <div class="form_control">
                        <label class="f_label">手机</label>
                        <div class="controls">
                          	  <input  type="hidden" name="url" id="url" value="${specialSubject.encodeSpUrl}"/>
                             <input type="text" name="phone" class="inpt" maxlength="11" placeholder="请输入购车人手机号" >
                             <span class="help-inline"></span>
                        </div>
                    </div>
                    <div class="form_control">
                        <label class="f_label">&nbsp;</label>
                        <div class="controls">
                               <button type="submit" class="g-btn g-btn-l g-btn-sure"><span>团购报名</span></button>
                        </div>
                    </div>
                </form>	
            </div>
            <div class="sbw_right fr">
            	<div class="seo_info_con">
                    <ul>
                        <li>
                            <p class="bold">网络报价</p>
                            <p>水分太大</p>
                            <i class="seo_ico seo_ico_error"></i>
                        </li>
                        <li>
                            <p class="bold">打电话到4S店询价</p>
                            <p>打死都不告诉你真实成交价</p>
                            <i class="seo_ico seo_ico_error"></i>
                        </li>
                        <li>
                            <p class="bold">到4S店询价格</p>
                            <p>砍到吐血也只能拿到加价的价格</p>
                            <i class="seo_ico seo_ico_error"></i>
                        </li>
                        <li>
                            <p class="bold">团车网报名</p>
                            <p>无论现在买车还是以后买，</p>
                            <p>都随时随地拿到最真实的市场成交价</p>
                            <i class="seo_ico seo_ico_success"></i>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>